#!/usr/bin/env python3

import pathlib
import io
import os
import re
import sys
import math
import copy
import enum
import random
import shutil
import argparse
import configparser
from decimal import Decimal as D
from datetime import datetime, timedelta
from typing import Callable, Mapping, List, Tuple, Union
import tkinter as tk


class Dim(enum.Enum):
    '''
    Map cartesian cardinals to integers
    '''
    x = 0
    y = 1
    z = 2  # For polycubes


class Rotation(enum.Enum):
    '''
    Enumerate available rotations
    '''
    identity = 0
    cw = 1  # π/2 clockwise
    ccw = 2  # π/2 counterclockwise


class Translation(enum.Enum):
    '''
    Enumerate available translations
    '''
    identity = 0
    # Single row/column translations
    left = 3  # One column left
    right = 4  # One column right
    down = 5  # One row down
    # Extremal translations
    min = 6  # Left side
    max = 7  # Right side
    bottom = 8  # Bottom side


class GameState(enum.Enum):
    '''
    Enumerate game states
    '''
    running = 0
    paused = 1
    over = 2


class EventType(enum.Enum):
    '''
    Enumerate available asynchronous events
    '''
    iterate = 1
    remove = 2


class Colors(dict):
    '''
    Store color information used for displaying polyominos in the game
    '''
    def __init__(self, normal:str, light:str, dark:str):
        self['normal'] = normal
        self['light'] = light
        self['dark'] = dark


class Grid:
    '''
    The rectangular region of squares that comprises the game state.  The
    squares map to the integer coordinates in the first quadrant of the
    cartesian plane such that each square is represented by the (integral)
    point at its upper right corner.  The origin corresponds to the upper right
    corner of the lower left square of the grid
    '''
    def __init__(self, opts:Mapping, width:int, height:int):
        '''
        Setup game grid
        '''
        # Store program options
        self.opts:Mapping = opts

        # Initialize internal grid
        self._grid:List[List[Mapping]] = [[{'type': None, 'id': None, 'colors': {}, 'is_active': None} for i in range(height)] for j in range(width)]
        self.width:int = len(self._grid)
        self.height:int = len(self._grid[0])

    def __check_nonnegative(self, v:Tuple[int, int])->None:
        '''
        Disallow accessing squares by negative coordinates.  Python allows
        accessing elements of iterables by one modulus below the residual
        representation of the array, but we disallow it for simplicity
        '''
        if 0 > min(v):
            raise IndexError('grid coordinates must be nonnegative')

    def __getitem__(self, v:Tuple[int, int])->dict:
        '''
        Retrieve the square details at coordinates v from the origin
        '''
        self.__check_nonnegative(v)
        return self._grid[v[0]][v[1]]

    def __setitem__(self, v:Tuple[int, int], d:Mapping)->None:
        '''
        Update the square at coordinates v from the origin to be of tetromino
        type t with Tkinter item id i, where d is a dictionary of the form
        {'type': t, 'id': i)
        '''
        self.__check_nonnegative(v)
        self._grid[v[0]][v[1]].update(d)

    def __iter__(self)->Tuple[int, int, dict]:
        '''
        Iterate over the grid squares, providing both the coordinates and the
        square info
        '''
        for x in range(self.width):
            for y in range(self.height):
                yield (x, y), self[x, y]

    def print(self)->None:
        '''
        Display grid state
        '''
        # Convert columns to rows
        rows:Mapping = {}
        for v, square in self:
            if not v[1] in rows:
                rows[v[1]] = {}
            rows[v[1]][v[0]] = ' ' if square['type'] is None else square['type']
        for i, row in enumerate(rows):
            rows[i] = ''.join([2*rows[i][j] if len(rows[i][j]) == 1 else rows[i][j][:2] for j in sorted(rows[i].keys())])

        # Print rows with formatting
        digits:int = len(str(self.opts['board']['height']))
        row_fmt:str = '{{:0{}}}'.format(digits)
        print(digits*' ' + '+' + 2*len(self._grid)*'-' + '+')
        for i in reversed(list(rows.keys())):
            print(row_fmt.format(self.opts['board']['height'] - i - 1) + '|' + rows[i] + '|')
        print(digits*' ' + '+' + 2*len(self._grid)*'-' + '+')


class Polyomino:
    r'''
    Define a polyomino by coordinates to the upper right corner of each of its
    squares and provide the valid transformations for a polyomino on the
    $\mathbb Z^2$ lattice
    '''
    def __init__(self, name:str, colors:Colors, coords:List[Tuple[D, D]]):
        '''
        Setup attributes and coordinates
        '''
        self.name:str = name
        self.colors:Colors = colors

        # To minimize the distance between the polyomino proper origin and the
        # polyomino center of mass, coordinates can take integral and
        # half-integral values
        if any([v[0]%1 or v[1]%1 for v in coords]):
            self.coords:List[Tuple[D, D]] = [[int(v[0] + D('-0.5')), int(v[1] + D('-0.5'))] for v in coords]
            self.o:List[D] = [D('-0.5'), D('-0.5')]
        else:
            self.coords:List[Tuple[D, D]] = coords
            self.o:List[D] = [0, 0]
        self.ordinal:int = len(coords)  # Polyomino ordinal (4 == tetromino, etc.)

    def _check_grid(self, coords:List[Tuple[int, int]], grid:Grid)->bool:
        '''
        Validate whether the coordinates, which correspond to the upper right
        corner of a polyomino square are all available in the grid
        '''
        for v in coords:
            # Check that v points to the interior of the grid
            try:
                grid[v]
            except IndexError:
                return False
            # Check that v points to an unoccupied square
            if grid[v]['type'] != None:
                return False
        return True

    def min(self, dim:Dim)->int:
        '''
        Return the minimum coordinate of the polyomino in the given dimension
        '''
        return min([c[dim.value] for c in self.coords])

    def max(self, dim:Dim)->int:
        '''
        Return the maximum coordinate of the polyomino in the given dimension
        '''
        return max([c[dim.value] for c in self.coords])

    def rotate(self, dir:Rotation, grid:Grid)->bool:
        '''
        Rotate polyomino clockwise or counterclockwise (±π/2) about its proper
        origin if the resulting transformation is contained within the grid and
        places the polyomino on unoccupied squares
        '''
        # Prepare new coordinates and rotation tensor
        coords:List[Tuple[D, D]] = [[0, 0] for i in range(self.ordinal)]
        sgn:int = {
            Rotation.cw: -1,
            Rotation.ccw: 1,
        }.get(dir)

        # Apply rotation tensor if possible
        for i in range(self.ordinal):
            coords[i][0] = int(-sgn*(self.coords[i][1] - self.o[1]) + self.o[0])
            coords[i][1] = int(sgn*(self.coords[i][0] - self.o[0]) + self.o[1])
        if self._check_grid(coords, grid):
            self.coords:List[Tuple[D, D]] = coords
            return True
        return False

    def translate(self, v:Union[Tuple[int, int], Translation], grid, incremental=False)->bool:
        '''
        Translate polyomino by the vector v if the resulting transformation
        places the polyomino within the grid and on unoccupied squares

        :param incremental: If true, move the polyomino one row/column at a
        time in the direction of v until the full translation, v, is achieved,
        or as far as possible along the direction of v
        '''
        # Redefine v as explicit coordinates in the grid reference frame
        if isinstance(v, Translation):
            v = {
                Translation.left: [-1, 0],
                Translation.right: [1, 0],
                Translation.down: [0, -1],
                Translation.min: [-self.min(Dim.x), 0],
                Translation.max: [grid.width - self.max(Dim.x) - 1, 0],
                Translation.bottom: [0, -self.min(Dim.y)],
            }.get(v)
        # Define unit form of v
        magnitude:D = D(math.sqrt(v[0]**2 + v[1]**2)) or 1  # Prevent zero division
        # Not really a unit in the dir of v, but a projection onto the grid;
        # corollary: this can only be one of nine possible values
        unit:Tuple[int, int] = [math.ceil(v[0]/magnitude), math.ceil(v[1]/magnitude)]

        # Prepare new coordinates and new proper origin in the grid frame
        coords:List[Tuple[D, D]] = [[0, 0] for i in range(self.ordinal)]
        o:Tuple[int, int] = [0, 0]

        # Incrementally apply upto translation vector v
        success:bool = False
        u:Tuple[int, int] = unit if incremental else v
        if u == [0, 0]:
            return success
        while True:
            for i in range(self.ordinal):
                coords[i][0] = self.coords[i][0] + u[0]
                coords[i][1] = self.coords[i][1] + u[1]
                o = [self.o[0] + u[0], self.o[1] + u[1]]
            if self._check_grid(coords, grid):
                self.coords = [[coord[0], coord[1]] for coord in coords]
                self.o = [o[0], o[1]]
                success = True
                if not incremental:
                    return success
            else:
                return success


tetrominoes = (
    Polyomino(
        name='Z',
        coords=[[D('-1.5'), 0], [D('-0.5'), 0], [D('-0.5'), -1], [D('0.5'), -1]],
        colors=Colors('#CC6666', '#F89FAB', '#803C3B'),
    ),
    Polyomino(
        name='S',
        coords=[[D('-0.5'), -1], [D('0.5'), -1], [D('0.5'), 0], [D('1.5'), 0]],
        colors=Colors('#66CC66', '#79FC79', '#3B803B'),
    ),
    Polyomino(
        name='l',
        coords=[[D('-1.5'), 0], [D('-0.5'), 0], [D('0.5'), 0], [D('1.5'), 0]],
        colors=Colors('#6666CC', '#7979FC', '#3B3B80'),
    ),
    Polyomino(
        name='T',
        coords=[[-1, 0], [0, 0], [0, -1], [1, 0]],
        colors=Colors('#CCCC66', '#FCFC79', '#80803B'),
    ),
    Polyomino(
        name='o',
        coords=[[D('-0.5'), D('0.5')], [D('-0.5'), D('-0.5')], [D('0.5'), D('0.5')], [D('0.5'), D('-0.5')]],
        colors=Colors('#CC66CC', '#FC79FC', '#803B80'),
    ),
    Polyomino(
        name='L',
        coords=[[-1, 1], [-1, 0], [-1, -1], [0, -1]],
        colors=Colors('#66CCCC', '#79FCFC', '#3B8080'),
    ),
    Polyomino(
        name='J',
        coords=[[0, 1], [0, 0], [0, -1], [-1, -1]],
        colors=Colors('#DAAA00', '#FCC600', '#806200'),
    ),
)


class PrecisionVar(tk.StringVar):
    '''
    Represent the value at the specified precision while maintaining the actual
    value at full precision
    '''
    def __init__(self, *args, precision:int=2, **kwargs):
        '''
        Setup PrecisionVar object
        '''
        self.precision:int = precision
        self.float_value:float = self._validate(kwargs.pop('value') if 'value' in kwargs else 0.0)
        super().__init__(*args, value=self._fmt(), **kwargs)

    def _validate(self, value:float)->float:
        '''
        Validate input value
        '''
        if isinstance(value, (int, float)) and value >= 0:
            return value
        else:
            raise TypeError('value must be a nonnegative number')

    def _fmt(self)->str:
        '''
        Format decimal string representation
        '''
        return '{{:.{}f}}'.format(self.precision).format(self.float_value)

    def get(self, raw:bool=False)->float:
        '''
        Get value formatted to specified precision
        '''
        return self.float_value if raw else super().get()

    def set(self, value:float=0.0)->None:
        '''
        Set value
        '''
        self.float_value:float = self._validate(value)
        super().set(self._fmt())


class TimerVar(tk.StringVar):
    '''
    Timer string widget variable with start/stop capability
    '''
    def __init__(self, *args, **kwargs):
        '''
        Setup TimeVar object
        '''
        self.set(kwargs.pop('value') if 'value' in kwargs else timedelta())
        super().__init__(*args, value=self._to_str(self.accumulated_elapsed), **kwargs)

    def _validate(self, value:timedelta)->timedelta:
        '''
        Validate input value
        '''
        if isinstance(value, timedelta):
            return value
        else:
            raise TypeError('value must be of type timedelta')

    def _to_str(self, value:timedelta)->str:
        '''
        Convert value timedelta to string without microseconds
        '''
        return str(value)[:7]

    def get(self, as_seconds:bool=False)->Union[str, tk.StringVar]:
        '''
        Get elapsed time as a string or as total seconds
        '''
        computed:timedelta = datetime.now() - self.active_counting_since + self.accumulated_elapsed
        super().set(self._to_str(computed))  # TkInter uses an internal method to get the value into a widget, so we need to update the parent value here
        return computed.total_seconds() if as_seconds else super().get()

    def set(self, value:timedelta=timedelta())->None:
        '''
        Reset the timer with a new value or update the value to the current
        time
        '''
        self.accumulated_elapsed:timedelta = value  # Reset active counter
        self.active_counting_since:timedelta = timedelta()  # Timestamp of last start/resume

    def start(self)->None:
        '''
        Begin/resume counting
        '''
        if not self.active_counting_since:  # Start action is idempotent
            self.active_counting_since:datetime = datetime.now()

    def stop(self)->None:
        '''
        Collect active counting into `accumulated_elapsed` and reset
        `active_counting_since`
        '''
        if self.active_counting_since:  # Stop action is idempotent
            self.accumulated_elapsed += datetime.now() - self.active_counting_since
            self.active_counting_since:timedelta = timedelta()


class Board(tk.Canvas):
    '''
    Used to display polyomino block grid
    '''
    @property
    def width(self)->int: return self.grid.width

    @property
    def height(self)->int: return self.grid.height

    def __init__(self, opts:Mapping, parent:tk.Frame, width:int, height:int, is_projection:bool=False):
        '''
        Setup board
        '''
        # Setup options
        self.opts:Mapping = opts
        self.is_projection:bool = is_projection
        self.border_width:int = self.opts['scale']//16
        self.aspect_proportion:int = 3 if self.is_projection else 1
        self.full_row_colors:Colors = Colors('#DDDDDD', '#FFFFFF', '#BBBBBB')
        self.pause_cover_id:int = 0

        # Setup internal grid
        self.grid:Grid = Grid(self.opts, width, height)

        # Setup TK
        super().__init__(parent,
                         width=self.opts['scale']*width,
                         height=self.opts['scale']*height//self.aspect_proportion)
        # Setup board widget
        self.create_rectangle(0, 0,
                              self.opts['scale']*width, self.opts['scale']*height,
                              fill='black',
                              outline='black',
                              width=self.border_width)

        if self.opts['debug']:
            for v, square in self.grid:
                u = self._transform_coord(v)
                self.create_text((self.opts['scale']*u[0], self.opts['scale']*u[1]),
                                 text='{},{}'.format(*u),
                                 fill='white', font=('Monospace', 5), anchor=tk.NW)

    def _transform_coord(self, v:Tuple[int, int])->Tuple[int, int]:
            '''
            tetratile treats the game board as the first quadrant of the Cartesian
            plane with the origin at the lower left corner, whereas Tkinter,
            conventionally, places the origin in the upper left corner, with
            positive x and y directions pointing right and down, respectively.

            This function transforms tetratile coordinates into Tkinter
            coordinates.
            '''
            return [v[0], self.height - 1 - v[1]]

    def _draw_square(self, v:Tuple[int, int], colors:Colors)->int:
        '''
        Draw or clear a polyomino square on the board at v
        '''
        u:Tuple[int, int] = self._transform_coord(v)
        u = [self.opts['scale']*u[0], self.opts['scale']*u[1]]
        return self.create_rectangle(
            u[0] + self.border_width, u[1] + self.border_width,
            u[0] + self.opts['scale'], u[1] + self.opts['scale']//self.aspect_proportion,
            fill=colors['normal'],
            outline=colors['dark'],
            width=self.border_width
        )

    def update(self, piece:Polyomino, clear:bool=False, is_active:bool=False)->None:
        '''
        Place or clear piece on the board
        '''
        for v in piece.coords:
            u = [v[0], 0] if self.is_projection else v
            square = self.grid[u]
            if clear:
                square.update({'type': None,
                               'id': self.delete(square['id']),
                               'colors': {},
                               'is_active': None})
            else:
                if not square['id']:
                    colors = piece.colors[v[0]] if piece.name == 'row' and not piece.full else piece.colors
                    square.update({'type': piece.name,
                                   'id': self._draw_square(u, colors),
                                   'colors': colors,
                                   'is_active': is_active})

    def select_full_rows(self)->bool:
        '''
        Mark full rows with full row colors prior to removing them

        .. note::

            There is a low probability race condition that between the time of
            marking and the time of removal, new rows could become filled by
            the introduction of a new piece, such that they are removed and not
            marked as the board does not persist calculated data, such as which
            rows are full, by design: this incidental data is stateless and
            must be recalculated whenever it is needed.  The severity of the
            race condition is asymptotically constant as the rates of each
            independent game thread: marking and removing, adding new pieces,
            scale proportionally.
        '''
        has_full_rows:bool = False
        for y in range(self.height):
            row_coords = [[x, y] for x in range(self.width) if self.grid[x, y]['type'] and not self.grid[x, y]['is_active']]
            if len(row_coords) == self.width:
                has_full_rows = True
                row:Polyomino = Polyomino('row', {v[0]: self.grid[v]['colors'] for v in row_coords}, row_coords)
                row.full = True
                row.colors = self.full_row_colors
                self.update(row, clear=True)
                self.update(row)
        return has_full_rows

    def _get_rows(self)->Tuple[int, List[Polyomino]]:
        '''
        Gather all full and partial rows
        '''
        rows:List[Polyomino] = []
        full_count:int = 0
        for y in range(self.height):
            row_coords = [[x, y] for x in range(self.width) if self.grid[x, y]['type'] and not self.grid[x, y]['is_active']]
            if len(row_coords):
                row:Polyomino = Polyomino('row', {v[0]: self.grid[v]['colors'] for v in row_coords}, row_coords)
                rows.append(row)
                row.full:bool = False
                row.full_below_count = full_count
            if len(row_coords) == self.width:
                full_count += 1
                row.full:bool = True
                row.colors = self.full_row_colors
                self.update(row, clear=True)
                self.update(row)
        return full_count, rows

    def remove_full_rows(self)->int:
        '''
        Remove full rows and move partial rows down into the vacancies; return
        number of removed rows
        '''
        full_count:int = None
        rows:List[Polyomino] = None
        full_count, rows = self._get_rows()
        for row in rows:
            if row.full:
                self.update(row, clear=True)
            elif row.full_below_count:
                self.update(row, clear=True)
                row.translate([0, -row.full_below_count], self.grid)
                self.update(row)
        return full_count

    def clear(self)->None:
        '''
        Remove all occupied squares from the board
        '''
        full_count:int = None
        rows:List[Polyomino] = None
        full_count, rows = self._get_rows()
        for row in rows:
            self.update(row, clear=True)

    def add_pause_cover(self)->None:
        '''
        Cover the board when game is paused
        '''
        if not self.pause_cover_id:
            self.pause_cover_id:int = self.create_rectangle(
                0, 0,
                self.opts['scale']*(self.width + 1),
                self.opts['scale']*(self.height + 1),
                fill='black',
                outline='black',
                width=0
            )

    def remove_pause_cover(self)->None:
        '''
        Uncover the board when game is paused
        '''
        if self.pause_cover_id > 0:
            self.delete(self.pause_cover_id)
            self.pause_cover_id = 0


class TetraTile(tk.Frame):
    '''
    Main game window
    '''
    def __init__(self, config:Mapping, master=None):
        '''
        Setup game
        '''
        # Setup options
        self.pdeg:int = 4  # Polyomino degree (hardcoded to tetromino)
        self.opts:Mapping = config.opts

        # Setup game data and state
        self.removed:Mapping[int, tk.IntVar] = {r + 1: tk.IntVar() for r in range(self.pdeg)}
        self.removed['total'] = tk.IntVar()

        self.used:Mapping[str, tk.IntVar] = {t.name: tk.IntVar() for t in tetrominoes}
        self.used['total'] = tk.IntVar()
        self.next_piece:Polyomino = None
        self.piece:Polyomino = None

        self.time_elapsed:TimeVar = TimerVar()
        self.time_elapsed.start()

        self.rate:PrecisionVar = PrecisionVar()
        self.piece_rate:PrecisionVar = PrecisionVar()
        self.row_rate:PrecisionVar = PrecisionVar()
        self._update_rates()
        self.state_name:tk.StringVar = tk.StringVar()
        self.set_state(GameState.running)

        # Setup TK
        super().__init__(master)
        self.master:tk.Frame = master
        self.pack()
        self.create_widgets()
        self.setup_events()
        self.add_piece()
        self.iterate_id:str = self._schedule(EventType.iterate)  # Start the game cycle

    def _schedule(self, event_type:EventType)->str:
        '''
        Schedule an asynchronous event
        '''
        if event_type == EventType.iterate:
            action:Callable = self.iterate
            rate:float = self.rate.get(raw=True)
        elif event_type == EventType.remove:
            action = self.remove_full_rows
            rate = self.rate.get(raw=True)*self.opts['remove_freq']

        return self.master.after(int(1e3/rate), action)  # Convert seconds to milliseconds

    def _update_removed(self, rows_removed:int)->None:
        '''
        Update the count of rows removed
        '''
        self.removed[rows_removed].set(self.removed[rows_removed].get() + 1)
        self.removed['total'].set(self.removed['total'].get() + rows_removed)

    def _update_rates(self)->None:
        '''
        Update computed rates
        '''
        new_rate:float = self.opts['initial_rate']*(1 if self.opts['constant'] else math.log(self.removed['total'].get()/2**4 + 2, 2))
        self.rate.set(max(new_rate, self.opts['min_rate']))
        self.piece_rate.set(self.used['total'].get()/(self.time_elapsed.get(as_seconds=True) or 1))
        self.row_rate.set(self.removed['total'].get()/(self.time_elapsed.get(as_seconds=True) or 1))

    def _update_piece_on_board(self, clear:bool=False, is_active:bool=True)->None:
        '''
        Place or clear piece and its projection or shadow on the board
        '''
        self.board.update(self.piece, clear=clear, is_active=is_active)
        if self.opts['shadow'] == 'projection':
            self.projection_board.update(self.piece, clear=clear, is_active=is_active)

    def create_widgets(self)->None:
        '''
        Pack in game widgets
        '''
        # Game frame
        self.game:tk.Frame = tk.Frame(self)
        self.game.pack(side='left')

        self.board:Board = Board(self.opts, self.game, self.opts['board']['width'], self.opts['board']['height'])
        self.board.pack(side='top')

        if self.opts['shadow'] == 'projection':
            self.projection_board:Board = Board(self.opts, self.game, self.opts['board']['width'], 1, is_projection=True)
            self.projection_board.pack(side='top')

        # Marquee frame
        self.marquee:tk.Frame = tk.Frame(self)
        self.marquee.pack(side='right', padx=self.opts['scale'], pady=self.opts['scale'])

        self.preview_frame:tk.LabelFrame = tk.LabelFrame(self.marquee, text='preview')
        self.preview_frame.pack(side='top')
        self.preview_board:Board = Board(self.opts, self.preview_frame, self.pdeg, self.pdeg)
        self.preview_board.pack(side='top')

        self.rate_frame:tk.LabelFrame = tk.LabelFrame(self.marquee, text='fall rate')
        self.rate_frame.pack(side='top')
        self.rate_display:tk.Label = tk.Label(self.rate_frame, textvariable=self.rate)
        self.rate_display.pack(side='left')
        self.rate_unit:tk.Label = tk.Label(self.rate_frame, text='blocks/sec')
        self.rate_unit.pack(side='left')

        self.piece_rate_frame:tk.LabelFrame = tk.LabelFrame(self.marquee, text='piece rate')
        self.piece_rate_frame.pack(side='top')
        self.piece_rate_display:tk.Label = tk.Label(self.piece_rate_frame, textvariable=self.piece_rate)
        self.piece_rate_display.pack(side='left')
        self.piece_rate_unit:tk.Label = tk.Label(self.piece_rate_frame, text='pieces/sec')
        self.piece_rate_unit.pack(side='left')

        self.row_rate_frame:tk.LabelFrame = tk.LabelFrame(self.marquee, text='row rate')
        self.row_rate_frame.pack(side='top')
        self.row_rate_display:tk.Label = tk.Label(self.row_rate_frame, textvariable=self.row_rate)
        self.row_rate_display.pack(side='left')
        self.row_rate_unit:tk.Label = tk.Label(self.row_rate_frame, text='rows/sec')
        self.row_rate_unit.pack(side='left')

        self.used_frame:tk.LabelFrame = tk.LabelFrame(self.marquee, text='pieces used')
        self.used_frame.pack(side='top')
        class Total : name:str = 'total'
        for t in tetrominoes + (Total(),):
            stack:Mapping[str, tk.Widget] = {}
            stack['frame'] = tk.Frame(self.used_frame, width=12)
            stack['frame'].pack(side='top')
            stack['quantity'] = tk.Label(stack['frame'], textvariable=self.used[t.name])
            stack['quantity'].pack(side='left')
            stack['unit'] = tk.Label(stack['frame'], text='{}{}'.format('' if t.name == 'total' else 'x', t.name))
            stack['unit'].pack(side='left')

        self.removed_frame = tk.LabelFrame(self.marquee, text='rows removed')
        self.removed_frame.pack(side='top')
        for r in list(range(1, self.pdeg + 1)) + ['total']:
            stack:Mapping[str, tk.Widget] = {}
            stack['frame'] = tk.Frame(self.removed_frame, width=12)
            stack['frame'].pack(side='top')
            stack['quantity'] = tk.Label(stack['frame'], textvariable=self.removed[r])
            stack['quantity'].pack(side='left')
            stack['unit'] = tk.Label(stack['frame'], text='{}{}'.format('' if r == 'total' else 'x', r))
            stack['unit'].pack(side='left')

        self.time_elapsed_frame:tk.LabelFrame = tk.LabelFrame(self.marquee, text='elapsed time')
        self.time_elapsed_frame.pack(side='top')
        self.time_elapsed_display:tk.Label = tk.Label(self.time_elapsed_frame, textvariable=self.time_elapsed, width=12)
        self.time_elapsed_display.pack(side='top')

        self.state_display:tk.Label = tk.Label(self.marquee, textvariable=self.state_name)
        self.state_display.pack(side='top')

    def set_state(self, state:GameState)->None:
        '''
        Set the game state
        '''
        self.state:GameState = state
        self.state_name.set({
            GameState.running: '',
            GameState.paused: 'paused',
            GameState.over: 'game over',
        }.get(state))

    def setup_events(self)->None:
        '''
        Respond to inputs and other game conditions: mainly key input
        '''
        for name, key in self.opts['keys'].items():
            self.master.bind(key, getattr(self, name))

    def pause(self, event:tk.Event)->None:
        '''
        (Un)pause the game.  This function is bound by `setup_events` to the
        key the user configures for pausing
        '''
        if self.state == GameState.running:
            self.after_cancel(self.iterate_id)
            self.time_elapsed.stop()
            for board in (self.board, self.preview_board, self.projection_board):
                board.add_pause_cover()
            self.set_state(GameState.paused)
        elif self.state == GameState.paused:
            self.iterate_id = self._schedule(EventType.iterate)
            self.time_elapsed.start()
            for board in (self.board, self.preview_board, self.projection_board):
                board.remove_pause_cover()
            self.set_state(GameState.running)

    def move(transformation:Union[Rotation, Translation])->Callable:
        '''
        Map keys to transformations on the current piece.  These functions are
        bound by `setup_events` to the keys the user configures for moving
        pieces
        '''
        def transform(self, event:tk.Event)->None:
            '''
            Transform the current piece
            '''
            if self.state == GameState.running:
                self.move_piece(transformation)
        return transform

    left:Callable = move(Translation.left)
    right:Callable = move(Translation.right)
    left_side:Callable = move(Translation.min)
    right_side:Callable = move(Translation.max)
    rotate_left:Callable = move(Rotation.ccw)
    rotate_right:Callable = move(Rotation.cw)
    down:Callable = move(Translation.down)
    drop:Callable = move(Translation.bottom)

    def restart(self)->None:
        '''
        Restart the game
        '''
        # Setup game state
        self.board.clear()
        self.projection_board.clear()
        self.piece:Polyomino = None

        for removed_counter in self.removed.values():
            removed_counter.set(0)
        for piece_counter in self.used.values():
            piece_counter.set(0)

        self.time_elapsed.set()
        self.time_elapsed.start()

        self._update_rates()
        self.set_state(GameState.running)

        # Setup TK
        self.restart_button.destroy()
        self.add_piece()
        self.iterate_id:str = self._schedule(EventType.iterate)

    def iterate(self)->None:
        '''
        Move the active piece one row down
        '''
        if self.state == GameState.paused:
            return
        if not self.move_piece(Translation.down):
            self._update_piece_on_board(clear=True)  # Remove active
            self._update_piece_on_board(is_active=False)  # Now inactive
            if self.board.select_full_rows():
                self._schedule(EventType.remove)
            self.add_piece()
        if self.opts['debug']:
            self.board.grid.print()
        if self.state == GameState.running:
            self._update_rates()
            self.iterate_id = self._schedule(EventType.iterate)
        elif self.state == GameState.over:
            self.restart_button = tk.Button(self.marquee, text='restart', command=self.restart)
            self.restart_button.pack(side='top')

    def add_piece(self)->None:
        '''
        Add a tetromino to the top center of the board
        '''
        def get_next_piece()->None:
            '''
            Get a new piece
            '''
            self.preview_board.clear()
            self.next_piece:Polyomino = copy.deepcopy(random.choice(tetrominoes))
            self.next_piece.translate(
                [
                    self.preview_board.width//2,
                    self.preview_board.height//2,
                ],
                self.preview_board.grid
            )
            self.preview_board.update(self.next_piece)

        if not self.next_piece:
            get_next_piece()
        self.piece:Polyomino = copy.deepcopy(self.next_piece)
        self.used[self.next_piece.name].set(self.used[self.next_piece.name].get() + 1)
        self.used['total'].set(self.used['total'].get() + 1)
        get_next_piece()

        if self.piece.translate(
                [
                    self.board.width//2 - self.preview_board.width//2,
                    self.board.height - 1 - self.piece.max(Dim.y),
                ],
                self.board.grid
            ):
            if self.opts['shadow'] == 'projection':
                self.projection_board.clear()
            self._update_piece_on_board()
        else:
            self.set_state(GameState.over)

    def move_piece(self, movement:Union[Rotation, Translation])->bool:
        '''
        Move current piece according to the movement requested:

        - (cw) Rotate π/2 clockwise about piece proper origin
        - (ccw) Rotate π/2 counterclockwise about piece proper origin
        - (left) One column left
        - (right) One column right
        - (down) One row down
        - (min) To the leftmost available position
        - (max) To the rightmost available position
        - (bottom) To the lowest available position
        '''
        transform:Union[Rotation, Translation] = None
        kwargs:Mapping[str, bool] = None
        # Map each movement to a predefined transformation on the current piece
        transform, kwargs = {
            Rotation.cw: (self.piece.rotate, {}),
            Rotation.ccw: (self.piece.rotate, {}),
            Translation.left: (self.piece.translate, {}),
            Translation.right: (self.piece.translate, {}),
            Translation.down: (self.piece.translate, {}),
            Translation.min: (self.piece.translate, {'incremental': True}),
            Translation.max: (self.piece.translate, {'incremental': True}),
            Translation.bottom: (self.piece.translate, {'incremental': True}),
        }.get(movement)
        # Execute the transformation on the current piece if possible
        self._update_piece_on_board(clear=True)
        result:bool = transform(movement, self.board.grid, **kwargs)
        # (Re)place
        self._update_piece_on_board()
        return result

    def remove_full_rows(self)->None:
        '''
        Remove full rows and move partial rows down into the vacancies
        '''
        full_count:int = self.board.remove_full_rows()
        self._update_removed(full_count)


class Preferences(tk.Frame):
    '''
    Dialog for editing game preferences
    '''
    def __init__(self):
        '''
        Setup preferences dialog
        '''
        raise NotImplementedError('Cannot create preferences dialog')


class Config:
    '''
    Provide and save game configuration
    '''
    def __init__(self, test:bool=False):
        '''
        Setup game configuration.  When `test == True`, command line arguments
        are not processed
        '''
        self.test:bool = test

        self.defaults:Mapping = {
            'config_file': self._get_xdg_config(),
            'debug': False,
            'board': {
                'scale': 32,  # [pixels/block] number of pixels per block side
                'width': 10,  # [blocks]
                'height': 22,  # [blocks]
            },
            'epsilon': sys.float_info.epsilon*3,  # Minimum float value allowed by game
            'min_rate': 0.2,  # Minimum allowed rate [blocks/second]
            'initial_rate': 1,  # Default initial rate [blocks/second]
            'remove_freq': 1,  # Number of game cycles to wait to remove a row after it becomes full
            'constant': False,  # Do not increase game rate
            'shadow': 'projection',  # TODO: proposition
            'keys': {
                'pause': 'p',
                'left': ',',
                'right': '.',
                'left_side': 'z',
                'right_side': '/',
                'rotate_left': 'm',
                'rotate_right': 'v',
                'down': 'x',
                'drop': 'c',
            }
        }
        self.opts:Mapping = self.get_opts()

    def _get_xdg_config(self)->pathlib.Path:
        '''
        Attempt to retrieve `$XDG_CONFIG_HOME`
        '''
        if 'XDG_CONFIG_HOME' in os.environ:
            return pathlib.Path(os.environ['XDG_CONFIG_HOME'])
        elif 'HOME' in os.environ:
            return pathlib.Path(os.environ['HOME'])/'.config'
        else:
            return pathlib.Path('.config')

    def _config_file(self, arg:str)->pathlib.Path:
        '''
        Create the parent path of the config file if it does not exist and
        return the path to the file
        '''
        path:pathlib.Path = pathlib.Path(arg)
        path.parent.mkdir(parents=True, exist_ok=True)
        return path

    def _size(self, arg:str)->Mapping[str, int]:
        '''
        Validate size argument
        '''
        # Match data
        size_pattern:str = (
            r'(?P<width>\d+)'   # width pixels
            r'(?P<mlt>[xX])'    # times
            r'(?P<height>\d+)'  # height pixels
        )
        match:re.Match = re.match(size_pattern, arg)

        # Validate size
        if not match:
            raise argparse.ArgumentTypeError('Incorrect size')

        # Construct return data and return
        board_size = {}
        for token in ('width', 'height'):
            value = match.group(token)
            board_size[token] = int(value) if value is not None else 0
        return board_size

    def _initial_rate(self, ir:str)->float:
        '''
        Verify that initial rate is >= minimum rate
        '''
        try:
            ir:float = float(ir)
        except ValueError:
            raise argparse.ArgumentTypeError('Initial rate is not a number: {}'.format(ir))
        if ir < self.defaults['min_rate']:
            raise argparse.ArgumentTypeError('Initial rate is too low: {}'.format(ir))
        else:
            return ir

    def _get_config(self, config_file:pathlib.Path)->dict:
        '''
        Read configs from config file
        '''
        # TODO: set opts equal to defaults, then override with config file values, then command line values
        opts:Mapping = {}
        config = configparser.ConfigParser()
        config.read(config_file)

        # Internal configs
        opts['epsilon'] = self.defaults['epsilon']

        # Window configs
        opts['board'] = {}
        if config.has_section('board'):
            opts['board']['scale'] = config.get('board', 'scale', vars=self.defaults)
            opts['board']['width'] = config.get('board', 'width', vars=self.defaults)
            opts['board']['height'] = config.get('board', 'height', vars=self.defaults)
        else:
            opts['board']['scale'] = self.defaults['board']['scale']
            opts['board']['width'] = self.defaults['board']['width']
            opts['board']['height'] = self.defaults['board']['height']

        # Game configs
        if config.has_section('game'):
            opts['debug'] = config.get('game', 'debug', vars=self.defaults)
            opts['min_rate'] = config.get('game', 'min_rate', vars=self.defaults)
            opts['initial_rate'] = config.get('game', 'initial_rate', vars=self.defaults)
            opts['constant'] = config.get('game', 'constant', vars=self.defaults)
            opts['remove_freq'] = config.get('game', 'remove_freq', vars=self.defaults)
            opts['shadow'] = config.get('game', 'shadow', vars=self.defaults)
        else:
            opts['debug'] = self.defaults['debug']
            opts['min_rate'] = self.defaults['min_rate']
            opts['initial_rate'] = self.defaults['initial_rate']
            opts['constant'] = self.defaults['constant']
            opts['remove_freq'] = self.defaults['remove_freq']
            opts['shadow'] = self.defaults['shadow']

        # Keys configs
        opts['keys'] = {}
        if config.has_section('keys'):
            for key in opts['keys'].keys():
                opts['keys'][key] = config.get('keys', key, vars=self.defaults['keys'])
        else:
            opts['keys'] = self.defaults['keys']

        return opts

    def _get_args(self)->dict:
        '''
        Read configs from command line
        '''
        desc='Polyomino tessellation game written in python+Tkinter'
        arg_parser = argparse.ArgumentParser(description=desc,
                                    formatter_class=argparse.ArgumentDefaultsHelpFormatter)
        arg_parser.add_argument('-c', '--config-file',
                                default=self.defaults['config_file'],
                                type=self._config_file,
                                help='Specify location of the config file')
        arg_parser.add_argument('-d', '--debug',
                                default=self.defaults['debug'],
                                action='store_true',
                                help='Run game in debug mode')
        arg_parser.add_argument('-s', '--size',
                                default='{0[width]}x{0[height]}'.format(self.defaults['board']),
                                type=self._size,
                                help='Board size [blocks^2]')
        arg_parser.add_argument('-a', '--scale',
                                default=self.defaults['board']['scale'],
                                type=int,
                                help='Board scale [pixels/block]')
        arg_parser.add_argument('-r', '--initial-rate',
                                default=self.defaults['initial_rate'],
                                type=self._initial_rate,
                                help='Initial rate: must be >= {} [blocks/second]'.format(self.defaults['min_rate']))
        arg_parser.add_argument('-o', '--constant',
                                default=self.defaults['constant'],
                                action='store_true',
                                help='Do not increase game rate')
        return vars(arg_parser.parse_args())

    def get_opts(self)->dict:
        '''
        Setup program options
        '''
        # Config resolution:
        # 0. programmatic defaults
        # 1. dynamically set programmatic values
        # 2. config file values
        # 3. command line values
        args:Mapping = self.defaults if self.test else self._get_args()
        opts:Mapping = self._get_config(args['config_file'])
        opts.update(args)
        return opts

    def write_opts(self, opts):
        '''
        Save game configs to file when config dialog is closed
        '''
        raise NotImplementedError('Cannot save game preferences')


def tetratile()->None:
    '''
    Execute the game
    '''
    try:
        TetraTile(Config(), master=tk.Tk(className='tetratile')).mainloop()
    except KeyboardInterrupt:
        exit(0)


if __name__ == '__main__' : tetratile()
